version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    versioning-strategy: widen
    labels:
      - "npm v1"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "dev"
    versioning-strategy: widen
    # Labels on pull requests for version updates only
    labels:
      - "npm v0"